// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Transit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Transidious.Serialization {

  /// <summary>Holder for reflection information generated from Transit.proto</summary>
  public static partial class TransitReflection {

    #region Descriptor
    /// <summary>File descriptor for Transit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TransitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1UcmFuc2l0LnByb3RvEhlUcmFuc2lkaW91cy5TZXJpYWxpemF0aW9uGgxD",
            "b21tb24ucHJvdG8i2gEKBExpbmUSNwoJbWFwT2JqZWN0GAEgASgLMiQuVHJh",
            "bnNpZGlvdXMuU2VyaWFsaXphdGlvbi5NYXBPYmplY3QSNAoEdHlwZRgCIAEo",
            "DjImLlRyYW5zaWRpb3VzLlNlcmlhbGl6YXRpb24uVHJhbnNpdFR5cGUSDwoH",
            "ZGVwb3RJRBgDIAEoDRIPCgdzdG9wSURzGAQgAygNEhAKCHJvdXRlSURzGAUg",
            "AygNEi8KBWNvbG9yGAYgASgLMiAuVHJhbnNpZGlvdXMuU2VyaWFsaXphdGlv",
            "bi5Db2xvciJ1CgRTdG9wEjcKCW1hcE9iamVjdBgBIAEoCzIkLlRyYW5zaWRp",
            "b3VzLlNlcmlhbGl6YXRpb24uTWFwT2JqZWN0EjQKCHBvc2l0aW9uGAIgASgL",
            "MiIuVHJhbnNpZGlvdXMuU2VyaWFsaXphdGlvbi5WZWN0b3IyIkAKBVJvdXRl",
            "EjcKCW1hcE9iamVjdBgBIAEoCzIkLlRyYW5zaWRpb3VzLlNlcmlhbGl6YXRp",
            "b24uTWFwT2JqZWN0KlkKC1RyYW5zaXRUeXBlEgcKA0J1cxAAEggKBFRyYW0Q",
            "ARIKCgZTdWJ3YXkQAhIRCg1JbnRlcmNpdHlSYWlsEAMSCQoFRmVycnkQBBIN",
            "CglMaWdodFJhaWwQBUIcqgIZVHJhbnNpZGlvdXMuU2VyaWFsaXphdGlvbmIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Transidious.Serialization.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Transidious.Serialization.TransitType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Transidious.Serialization.Line), global::Transidious.Serialization.Line.Parser, new[]{ "MapObject", "Type", "DepotID", "StopIDs", "RouteIDs", "Color" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Transidious.Serialization.Stop), global::Transidious.Serialization.Stop.Parser, new[]{ "MapObject", "Position" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Transidious.Serialization.Route), global::Transidious.Serialization.Route.Parser, new[]{ "MapObject" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TransitType {
    /// <summary>
    //// A bus line.
    /// </summary>
    [pbr::OriginalName("Bus")] Bus = 0,
    /// <summary>
    //// A tram line.
    /// </summary>
    [pbr::OriginalName("Tram")] Tram = 1,
    /// <summary>
    //// A subway line.
    /// </summary>
    [pbr::OriginalName("Subway")] Subway = 2,
    /// <summary>
    //// A regional train line.
    /// </summary>
    [pbr::OriginalName("IntercityRail")] IntercityRail = 3,
    /// <summary>
    //// A ferry line.
    /// </summary>
    [pbr::OriginalName("Ferry")] Ferry = 4,
    /// <summary>
    //// A light rail line.
    /// </summary>
    [pbr::OriginalName("LightRail")] LightRail = 5,
  }

  #endregion

  #region Messages
  public sealed partial class Line : pb::IMessage<Line> {
    private static readonly pb::MessageParser<Line> _parser = new pb::MessageParser<Line>(() => new Line());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Line> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Transidious.Serialization.TransitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Line() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Line(Line other) : this() {
      mapObject_ = other.mapObject_ != null ? other.mapObject_.Clone() : null;
      type_ = other.type_;
      depotID_ = other.depotID_;
      stopIDs_ = other.stopIDs_.Clone();
      routeIDs_ = other.routeIDs_.Clone();
      color_ = other.color_ != null ? other.color_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Line Clone() {
      return new Line(this);
    }

    /// <summary>Field number for the "mapObject" field.</summary>
    public const int MapObjectFieldNumber = 1;
    private global::Transidious.Serialization.MapObject mapObject_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Transidious.Serialization.MapObject MapObject {
      get { return mapObject_; }
      set {
        mapObject_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::Transidious.Serialization.TransitType type_ = global::Transidious.Serialization.TransitType.Bus;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Transidious.Serialization.TransitType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "depotID" field.</summary>
    public const int DepotIDFieldNumber = 3;
    private uint depotID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint DepotID {
      get { return depotID_; }
      set {
        depotID_ = value;
      }
    }

    /// <summary>Field number for the "stopIDs" field.</summary>
    public const int StopIDsFieldNumber = 4;
    private static readonly pb::FieldCodec<uint> _repeated_stopIDs_codec
        = pb::FieldCodec.ForUInt32(34);
    private readonly pbc::RepeatedField<uint> stopIDs_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<uint> StopIDs {
      get { return stopIDs_; }
    }

    /// <summary>Field number for the "routeIDs" field.</summary>
    public const int RouteIDsFieldNumber = 5;
    private static readonly pb::FieldCodec<uint> _repeated_routeIDs_codec
        = pb::FieldCodec.ForUInt32(42);
    private readonly pbc::RepeatedField<uint> routeIDs_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<uint> RouteIDs {
      get { return routeIDs_; }
    }

    /// <summary>Field number for the "color" field.</summary>
    public const int ColorFieldNumber = 6;
    private global::Transidious.Serialization.Color color_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Transidious.Serialization.Color Color {
      get { return color_; }
      set {
        color_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Line);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Line other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MapObject, other.MapObject)) return false;
      if (Type != other.Type) return false;
      if (DepotID != other.DepotID) return false;
      if(!stopIDs_.Equals(other.stopIDs_)) return false;
      if(!routeIDs_.Equals(other.routeIDs_)) return false;
      if (!object.Equals(Color, other.Color)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (mapObject_ != null) hash ^= MapObject.GetHashCode();
      if (Type != global::Transidious.Serialization.TransitType.Bus) hash ^= Type.GetHashCode();
      if (DepotID != 0) hash ^= DepotID.GetHashCode();
      hash ^= stopIDs_.GetHashCode();
      hash ^= routeIDs_.GetHashCode();
      if (color_ != null) hash ^= Color.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (mapObject_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MapObject);
      }
      if (Type != global::Transidious.Serialization.TransitType.Bus) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (DepotID != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(DepotID);
      }
      stopIDs_.WriteTo(output, _repeated_stopIDs_codec);
      routeIDs_.WriteTo(output, _repeated_routeIDs_codec);
      if (color_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Color);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (mapObject_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MapObject);
      }
      if (Type != global::Transidious.Serialization.TransitType.Bus) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (DepotID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DepotID);
      }
      size += stopIDs_.CalculateSize(_repeated_stopIDs_codec);
      size += routeIDs_.CalculateSize(_repeated_routeIDs_codec);
      if (color_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Color);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Line other) {
      if (other == null) {
        return;
      }
      if (other.mapObject_ != null) {
        if (mapObject_ == null) {
          MapObject = new global::Transidious.Serialization.MapObject();
        }
        MapObject.MergeFrom(other.MapObject);
      }
      if (other.Type != global::Transidious.Serialization.TransitType.Bus) {
        Type = other.Type;
      }
      if (other.DepotID != 0) {
        DepotID = other.DepotID;
      }
      stopIDs_.Add(other.stopIDs_);
      routeIDs_.Add(other.routeIDs_);
      if (other.color_ != null) {
        if (color_ == null) {
          Color = new global::Transidious.Serialization.Color();
        }
        Color.MergeFrom(other.Color);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (mapObject_ == null) {
              MapObject = new global::Transidious.Serialization.MapObject();
            }
            input.ReadMessage(MapObject);
            break;
          }
          case 16: {
            Type = (global::Transidious.Serialization.TransitType) input.ReadEnum();
            break;
          }
          case 24: {
            DepotID = input.ReadUInt32();
            break;
          }
          case 34:
          case 32: {
            stopIDs_.AddEntriesFrom(input, _repeated_stopIDs_codec);
            break;
          }
          case 42:
          case 40: {
            routeIDs_.AddEntriesFrom(input, _repeated_routeIDs_codec);
            break;
          }
          case 50: {
            if (color_ == null) {
              Color = new global::Transidious.Serialization.Color();
            }
            input.ReadMessage(Color);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Stop : pb::IMessage<Stop> {
    private static readonly pb::MessageParser<Stop> _parser = new pb::MessageParser<Stop>(() => new Stop());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Stop> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Transidious.Serialization.TransitReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Stop() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Stop(Stop other) : this() {
      mapObject_ = other.mapObject_ != null ? other.mapObject_.Clone() : null;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Stop Clone() {
      return new Stop(this);
    }

    /// <summary>Field number for the "mapObject" field.</summary>
    public const int MapObjectFieldNumber = 1;
    private global::Transidious.Serialization.MapObject mapObject_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Transidious.Serialization.MapObject MapObject {
      get { return mapObject_; }
      set {
        mapObject_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 2;
    private global::Transidious.Serialization.Vector2 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Transidious.Serialization.Vector2 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Stop);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Stop other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MapObject, other.MapObject)) return false;
      if (!object.Equals(Position, other.Position)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (mapObject_ != null) hash ^= MapObject.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (mapObject_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MapObject);
      }
      if (position_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Position);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (mapObject_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MapObject);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Stop other) {
      if (other == null) {
        return;
      }
      if (other.mapObject_ != null) {
        if (mapObject_ == null) {
          MapObject = new global::Transidious.Serialization.MapObject();
        }
        MapObject.MergeFrom(other.MapObject);
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Transidious.Serialization.Vector2();
        }
        Position.MergeFrom(other.Position);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (mapObject_ == null) {
              MapObject = new global::Transidious.Serialization.MapObject();
            }
            input.ReadMessage(MapObject);
            break;
          }
          case 18: {
            if (position_ == null) {
              Position = new global::Transidious.Serialization.Vector2();
            }
            input.ReadMessage(Position);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Route : pb::IMessage<Route> {
    private static readonly pb::MessageParser<Route> _parser = new pb::MessageParser<Route>(() => new Route());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Route> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Transidious.Serialization.TransitReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Route() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Route(Route other) : this() {
      mapObject_ = other.mapObject_ != null ? other.mapObject_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Route Clone() {
      return new Route(this);
    }

    /// <summary>Field number for the "mapObject" field.</summary>
    public const int MapObjectFieldNumber = 1;
    private global::Transidious.Serialization.MapObject mapObject_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Transidious.Serialization.MapObject MapObject {
      get { return mapObject_; }
      set {
        mapObject_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Route);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Route other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MapObject, other.MapObject)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (mapObject_ != null) hash ^= MapObject.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (mapObject_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MapObject);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (mapObject_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MapObject);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Route other) {
      if (other == null) {
        return;
      }
      if (other.mapObject_ != null) {
        if (mapObject_ == null) {
          MapObject = new global::Transidious.Serialization.MapObject();
        }
        MapObject.MergeFrom(other.MapObject);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (mapObject_ == null) {
              MapObject = new global::Transidious.Serialization.MapObject();
            }
            input.ReadMessage(MapObject);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
